version: "3.3"

services:
  # Wordpress
  simple-fsite-wp:
    image: wordpress:latest
    container_name: simple-fsite-wp
    restart: always
    working_dir: /var/www/html/
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: simple-fsite-mysql:3306
      WORDPRESS_DB_NAME: simple-fsite
      WORDPRESS_DB_USER: simple
      WORDPRESS_DB_PASSWORD: simple
    networks:
      - simple-network

  # MySQL db
  simple-fsite-mysql:
    image: mysql:5.7.22
    container_name: simple-fsite-mysql
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: simple
      MYSQL_DATABASE: simple-fsite
      MYSQL_USER: simple
      MYSQL_PASSWORD: simple
    networks:
      - simple-network
    volumes:
      db_data: {}


